Mentoring/Mentoring/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AutoMapper;
using Mentoring.Models;
using Mentoring.Services.DataProvider;
using Mentoring.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Mentoring.Controllers
{
    public class CategoriesController : Controller
    {
		private IDataProvider<Category> _dataProvider;
	    private IMapper _mapper;

	    public CategoriesController(IDataProvider<Category> dataProvider, IMapper mapper)
	    {
		    _dataProvider = dataProvider;
		    _mapper = mapper;
	    }

	    public IActionResult Index()
	    {
		    IQueryable<Category> categories = _dataProvider.GetData();
			List<CategoryViewModel> model = new List<CategoryViewModel>();
			foreach (Category category in categories)
			{
				model.Add(_mapper.Map<CategoryViewModel>(category));
			}

			return View(model);
		}

	    public IActionResult Image(int id)
	    {
		    Category category = _dataProvider.GetData().FirstOrDefault(c => c.CategoryId == id);
		    return File(category?.Picture?.ToArray() ?? new byte[0], "image/png");
	    }

	    public IActionResult EditImage(int id)
	    {
		    Category category = _dataProvider.GetData().FirstOrDefault(c => c.CategoryId == id);
		    CategoryViewModel model = _mapper.Map<CategoryViewModel>(category);
		    return View(model);
	    }

		[HttpPost]
	    public IActionResult EditImage(CategoryViewModel model, IFormFile picture)
	    {
		    if (!ModelState.IsValid)
			    return View(nameof(EditImage), model);

		    Category category = _dataProvider.GetData().FirstOrDefault(c => c.CategoryId == model.CategoryId);
		    if (category == null || picture == null)
			    return RedirectToAction(nameof(Index));

		    using (MemoryStream memoryStream = new MemoryStream())
		    {
			    picture.CopyTo(memoryStream);
			    category.Picture = memoryStream.ToArray();
		    }

		    _dataProvider.Update();

		    return RedirectToAction(nameof(Index));
	    }
	}
}

Mentoring/Mentoring/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Mentoring.Models;
using Mentoring.Services.ConfigReader;
using Mentoring.Services.DataProvider;
using Mentoring.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Mentoring.Controllers
{
	public class ProductsController : Controller
	{
		private IDataProvider<Product> _productDataProvider;
		private IDataProvider<Supplier> _supplierDataProvider;
		private IDataProvider<Category> _categoryDataProvider;
		private IConfigReader _configReader;
		private IMapper _mapper;

		public ProductsController(IDataProvider<Product> productDataProvider, IConfigReader configReader,
			IDataProvider<Supplier> supplierDataProvider, IDataProvider<Category> categoryDataProvider, IMapper mapper)
		{
			_productDataProvider = productDataProvider;
			_configReader = configReader;
			_supplierDataProvider = supplierDataProvider;
			_categoryDataProvider = categoryDataProvider;
			_mapper = mapper;
		}

		public IActionResult Index()
		{
			IQueryable<Product> products = _productDataProvider.GetData();
			int maxProductsCount = _configReader.GetMaxProductCount();
			if (maxProductsCount > 0)
				products = products.Take(maxProductsCount);

			List<ProductsViewModel> model = new List<ProductsViewModel>();
			foreach (Product product in products)
			{
				model.Add(_mapper.Map<ProductsViewModel>(product));
			}

			return View(model);
		}

		[HttpGet]
		public IActionResult CreateProduct()
		{
			CreateEditProductViewModel model = new CreateEditProductViewModel();
			CreateProductSelectLists(model);
			return View(model);
		}

		[HttpPost]
		public IActionResult CreateProduct(CreateEditProductViewModel model)
		{
			if (ModelState.IsValid)
			{
				Product newProduct = _mapper.Map<Product>(model);
				_productDataProvider.Add(newProduct);

				return RedirectToAction(nameof(Index));
			}
			else
			{
				CreateProductSelectLists(model);
				return View(model);
			}
		}

		[HttpGet]
		public IActionResult EditProduct(int id)
		{
			Product product = _productDataProvider.GetData().FirstOrDefault(p => p.ProductId == id);
			if (product != null)
			{
				CreateEditProductViewModel model = _mapper.Map<CreateEditProductViewModel>(product);
				CreateProductSelectLists(model);
				return View(nameof(CreateProduct), model);
			}
			else
			{
				return RedirectToAction(nameof(Index));
			}
		}

		[HttpPost]
		public IActionResult EditProduct(CreateEditProductViewModel model)
		{
			if (!ModelState.IsValid)
			{
				CreateProductSelectLists(model);
				return View(nameof(CreateProduct), model);
			}

			Product product = _productDataProvider.GetData().FirstOrDefault(p => p.ProductId == model.ProductId);
			if (product == null)
				return RedirectToAction(nameof(Index));

			product.CategoryId = model.CategoryId;
			product.Discontinued = model.Discontinued;
			product.ProductName = model.ProductName;
			product.QuantityPerUnit = model.QuantityPerUnit;
			product.ReorderLevel= model.ReorderLevel;
			product.SupplierId = model.SupplierId;
			product.UnitPrice = model.UnitPrice;
			product.UnitsInStock = model.UnitsInStock;
			product.UnitsOnOrder = model.UnitsOnOrder;
			_productDataProvider.Update();

			return RedirectToAction(nameof(Index));
		}

		private void CreateProductSelectLists(CreateEditProductViewModel model)
		{
			model.Category = new SelectList(_categoryDataProvider.GetData(), "CategoryId", "CategoryName");
			model.Supplier = new SelectList(_supplierDataProvider.GetData(), "SupplierId", "CompanyName");
		}
	}
}

Mentoring/Mentoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mentoring</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Mentoring</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
				<li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
			</ul>
			<partial name="_LoginPartial" />
		</div>
	</div>
</nav>
<partial name="_CookieConsentPartial"/>
<header class="modal-header">
	@if (IsSectionDefined("Header"))
	{
		RenderSection("Header", false);
	}
	else
	{
		<H1>This is default header</H1>
	}
</header>
<div>
	@await Component.InvokeAsync("Breadcrumbs")
</div>
<div class="container body-content">
	@RenderBody()
	<hr/>
	<footer>
		@if (IsSectionDefined("Footer"))
		{
			RenderSection("Footer", false);
		}
		else
		{
			<p>&copy; 2019 - Mentoring</p>
		}
	</footer>
</div>

<environment include="Development">
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
	<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
	        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
	        asp-fallback-test="window.jQuery"
	        crossorigin="anonymous"
	        integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
	</script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
	        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
	        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
	        crossorigin="anonymous"
	        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
	</script>
	<script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
<partial name="_ValidationScriptsPartial"/>
</body>
</html>

Mentoring/Mentoring/Views/Shared/_Layout_NoSections.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mentoring</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Mentoring</a>
            </div>
            <div class="navbar-collapse collapse">
	            <ul class="nav navbar-nav">
		            <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
		            <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
	            </ul>
	            <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
	       <img src="images/banner1.svg"/>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
	<partial name="_ValidationScriptsPartial" />
</body>
</html>